# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Design System
subtitle: The Australian Financial Review
email:
description: > # this means to ignore newlines until "baseurl:"

baseurl: /styleguide-afr # the subpath of your site, e.g. /blog

collections:
    section_frontpage:
        output: true
    section_brand:
        output: true
    section_layout:
        output: true
    section_colours:
        output: true
    section_typography:
        output: true
    section_iconography:
        output: true
    section_form_elements:
        output: true
    section_components:
        output: true
    section_deprecated:
        output: true

# Build settings
markdown: kramdown
prose:
    siteurl: 'https://ffxstyleguide.github.io/styleguide-afr/'
    media: 'images'
    ignore: ['_includes','_layouts','_sass','_site','components','css','js','.gitignore']
sass:
    sass_dir: _sass
